# 🧹 Windows 11 Service Optimizer Script
# Run as Administrator

$ErrorActionPreference = 'Continue'
$scriptRoot = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
$logDirectory = Join-Path $scriptRoot 'logs'
$null = New-Item -ItemType Directory -Path $logDirectory -Force -ErrorAction SilentlyContinue

# Allocate the next sequential run number. Existing run/state files are never overwritten.
$runNumbers = @(Get-ChildItem -LiteralPath $scriptRoot -Filter 'optimizer-run-*.json' -File -ErrorAction SilentlyContinue | ForEach-Object {
    if ($_.BaseName -match '^optimizer-run-(\d+)$') { [int]$matches[1] }
})
$runNumber = if ($runNumbers.Count -gt 0) { (($runNumbers | Measure-Object -Maximum).Maximum + 1) } else { 1 }
$runId = '{0:D3}' -f $runNumber
$runStamp = Get-Date -Format 'yyyyMMdd-HHmmss'
$logPath = Join-Path $logDirectory "optimization-run-$runId-$runStamp.log"
$statePath = Join-Path $scriptRoot "optimizer-run-$runId.json"
$undoPath = Join-Path $scriptRoot "undo-run-$runId.ps1"

function Write-Log {
    param([string]$Message, [string]$Level = 'INFO')
    $line = "{0} [{1}] {2}" -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $Level, $Message
    Add-Content -LiteralPath $logPath -Value $line -Encoding UTF8
    Write-Host $Message
}

$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
    [Security.Principal.WindowsBuiltInRole]::Administrator
)
if (-not $isAdmin) {
    Write-Host '❌ This script must be run as Administrator.' -ForegroundColor Red
    exit 1
}

Write-Log "Starting Windows 11 Service Optimizer run #$runNumber."
Write-Log "Computer: $env:COMPUTERNAME; User: $env:USERDOMAIN\$env:USERNAME"
Write-Log "Log file: $logPath"

$privacyServices = @('DiagTrack', 'dmwappushservice', 'WerSvc')
$performanceServices = @('SysMain', 'WSearch')
$networkServices = @('RemoteRegistry', 'TermService', 'RoutingAndRemoteAccess', 'SharedAccess')
$gamingServices = @('XblAuthManager', 'XblGameSave', 'XboxNetApiSvc', 'XboxGipSvc')
$deviceServices = @('bthserv', 'lfsvc', 'MapsBroker', 'FrameServer', 'WbioSrvc', 'SCardSvr', 'SensorService', 'PhoneSvc')
$legacyServices = @('Fax', 'CscService', 'RetailDemo', 'Spooler', 'WpnService', 'DPS', 'wisvc', 'SessionEnv')
$allServices = @($privacyServices + $performanceServices + $networkServices + $gamingServices + $deviceServices + $legacyServices) | Select-Object -Unique

$serviceChanges = [System.Collections.Generic.List[object]]::new()
$taskChanges = [System.Collections.Generic.List[object]]::new()
$changed = 0
$skipped = 0

foreach ($svc in $allServices) {
    try {
        $service = Get-CimInstance -ClassName Win32_Service -Filter "Name='$svc'" -ErrorAction Stop
        if ($null -eq $service) { throw 'Service not found' }

        $originalStartMode = $service.StartMode
        $originalStatus = $service.State
        Stop-Service -Name $svc -Force -ErrorAction SilentlyContinue
        Set-Service -Name $svc -StartupType Disabled -ErrorAction Stop

        $serviceChanges.Add([pscustomobject]@{
            Name = $svc
            OriginalStartMode = $originalStartMode
            OriginalStatus = $originalStatus
        })
        $changed++
        Write-Log "DISABLED service $svc (previous startup mode: $originalStartMode; previous status: $originalStatus)."
    }
    catch {
        $skipped++
        Write-Log "SKIPPED service ${svc}: $($_.Exception.Message)" 'WARN'
    }
}

try {
    $telemetryTasks = @(Get-ScheduledTask -ErrorAction Stop | Where-Object {
        $_.TaskName -match 'Telemetry|CEIP|Customer'
    })

    foreach ($task in $telemetryTasks) {
        try {
            $originalState = [string]$task.State
            Disable-ScheduledTask -TaskName $task.TaskName -TaskPath $task.TaskPath -ErrorAction Stop | Out-Null
            $taskChanges.Add([pscustomobject]@{
                TaskName = $task.TaskName
                TaskPath = $task.TaskPath
                OriginalState = $originalState
            })
            Write-Log "DISABLED scheduled task $($task.TaskPath)$($task.TaskName) (previous state: $originalState)."
        }
        catch {
            Write-Log "SKIPPED scheduled task $($task.TaskPath)$($task.TaskName): $($_.Exception.Message)" 'WARN'
        }
    }
}
catch {
    Write-Log "Could not enumerate scheduled tasks: $($_.Exception.Message)" 'WARN'
}

$state = [pscustomobject]@{
    RunNumber = $runNumber
    GeneratedAt = (Get-Date).ToString('o')
    ComputerName = $env:COMPUTERNAME
    LogPath = $logPath
    UndoPath = $undoPath
    Services = @($serviceChanges)
    ScheduledTasks = @($taskChanges)
}
$state | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $statePath -Encoding UTF8

# Generate an undo script tied to this exact run, rather than a shared mutable state file.
@"
# Generated by Windows 11 Service Optimizer for run #$runNumber.
# Run this file as Administrator to restore the state captured before run #$runNumber.
`$ErrorActionPreference = 'Continue'
`$statePath = Join-Path (if (`$PSScriptRoot) { `$PSScriptRoot } else { Split-Path -Parent `$MyInvocation.MyCommand.Path }) '$([IO.Path]::GetFileName($statePath))'
if (-not (Test-Path -LiteralPath `$statePath)) { Write-Error "State file not found: `$statePath"; exit 1 }
`$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not `$isAdmin) { Write-Error 'This script must be run as Administrator.'; exit 1 }
`$state = Get-Content -LiteralPath `$statePath -Raw | ConvertFrom-Json
foreach (`$service in @(`$state.Services)) {
    try {
        `$startupType = switch (`$service.OriginalStartMode) { 'Auto' { 'Automatic' } 'Manual' { 'Manual' } 'Disabled' { 'Disabled' } default { 'Manual' } }
        Set-Service -Name `$service.Name -StartupType `$startupType -ErrorAction Stop
        if (`$service.OriginalStatus -eq 'Running') { Start-Service -Name `$service.Name -ErrorAction Stop }
        Write-Host "Restored service: `$(`$service.Name)" -ForegroundColor Green
    } catch { Write-Warning "Could not restore service `$(`$service.Name): `$(`$_.Exception.Message)" }
}
foreach (`$task in @(`$state.ScheduledTasks)) {
    try {
        if (`$task.OriginalState -eq 'Disabled') { Disable-ScheduledTask -TaskName `$task.TaskName -TaskPath `$task.TaskPath -ErrorAction Stop | Out-Null }
        else { Enable-ScheduledTask -TaskName `$task.TaskName -TaskPath `$task.TaskPath -ErrorAction Stop | Out-Null }
        Write-Host "Restored scheduled task: `$(`$task.TaskPath)`$(`$task.TaskName)" -ForegroundColor Green
    } catch { Write-Warning "Could not restore scheduled task `$(`$task.TaskPath)`$(`$task.TaskName): `$(`$_.Exception.Message)" }
}
Write-Host 'Undo completed. Review any warnings above.' -ForegroundColor Cyan
"@ | Set-Content -LiteralPath $undoPath -Encoding UTF8

# Keep a compatibility pointer for users who only know the old filename.
$latestPointer = Join-Path $scriptRoot 'undo-last-run.ps1'
@"
# Compatibility launcher for the most recent optimization run.
`$root = if (`$PSScriptRoot) { `$PSScriptRoot } else { Split-Path -Parent `$MyInvocation.MyCommand.Path }
`$latest = Get-ChildItem -LiteralPath `$root -Filter 'undo-run-*.ps1' -File | Sort-Object Name -Descending | Select-Object -First 1
if (`$null -eq `$latest) { Write-Error 'No numbered undo script was found.'; exit 1 }
& `$latest.FullName
"@ | Set-Content -LiteralPath $latestPointer -Encoding UTF8

Write-Log "Completed run #$runNumber. Services changed: $changed; services skipped: $skipped; scheduled tasks captured: $($taskChanges.Count)."
Write-Log "Undo script: $undoPath"
Write-Host "`n📄 Detailed log: $logPath" -ForegroundColor Cyan
Write-Host "↩️ Undo script for run #$runNumber: $undoPath" -ForegroundColor Yellow
