# 🧹 Windows 11 Service Optimizer Script
# Run as Administrator

$ErrorActionPreference = 'Continue'
$scriptRoot = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
$logDirectory = Join-Path $scriptRoot 'logs'
$null = New-Item -ItemType Directory -Path $logDirectory -Force -ErrorAction SilentlyContinue
$runStamp = Get-Date -Format 'yyyyMMdd-HHmmss'
$logPath = Join-Path $logDirectory "optimization-$runStamp.log"
$statePath = Join-Path $scriptRoot 'optimizer-last-run.json'
$undoPath = Join-Path $scriptRoot 'undo-last-run.ps1'

function Write-Log {
    param([string]$Message, [string]$Level = 'INFO')
    $line = "{0} [{1}] {2}" -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $Level, $Message
    Add-Content -LiteralPath $logPath -Value $line -Encoding UTF8
    Write-Host $Message
}

$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
    [Security.Principal.WindowsBuiltInRole]::Administrator
)
if (-not $isAdmin) {
    Write-Host "❌ This script must be run as Administrator." -ForegroundColor Red
    exit 1
}

Write-Log 'Starting Windows 11 Service Optimizer.'
Write-Log "Computer: $env:COMPUTERNAME; User: $env:USERDOMAIN\$env:USERNAME"
Write-Log "Log file: $logPath"

$privacyServices = @('DiagTrack', 'dmwappushservice', 'WerSvc')
$performanceServices = @('SysMain', 'WSearch')
$networkServices = @('RemoteRegistry', 'TermService', 'RoutingAndRemoteAccess', 'SharedAccess')
$gamingServices = @('XblAuthManager', 'XblGameSave', 'XboxNetApiSvc', 'XboxGipSvc')
$deviceServices = @('bthserv', 'lfsvc', 'MapsBroker', 'FrameServer', 'WbioSrvc', 'SCardSvr', 'SensorService', 'PhoneSvc')
$legacyServices = @('Fax', 'CscService', 'RetailDemo', 'Spooler', 'WpnService', 'DPS', 'wisvc', 'SessionEnv')
$allServices = @($privacyServices + $performanceServices + $networkServices + $gamingServices + $deviceServices + $legacyServices) | Select-Object -Unique

$serviceChanges = [System.Collections.Generic.List[object]]::new()
$taskChanges = [System.Collections.Generic.List[object]]::new()
$processed = 0
$changed = 0
$skipped = 0

foreach ($svc in $allServices) {
    $processed++
    try {
        $service = Get-CimInstance -ClassName Win32_Service -Filter "Name='$svc'" -ErrorAction Stop
        if ($null -eq $service) { throw 'Service not found' }

        $originalStartMode = $service.StartMode
        $originalStatus = $service.State
        $record = [pscustomobject]@{
            Name = $svc
            OriginalStartMode = $originalStartMode
            OriginalStatus = $originalStatus
        }

        $stopResult = Stop-Service -Name $svc -Force -ErrorAction SilentlyContinue
        Set-Service -Name $svc -StartupType Disabled -ErrorAction Stop
        $serviceChanges.Add($record)
        $changed++
        Write-Log "DISABLED service $svc (previous startup mode: $originalStartMode; previous status: $originalStatus)."
    }
    catch {
        $skipped++
        Write-Log "SKIPPED service $svc: $($_.Exception.Message)" 'WARN'
    }
}

try {
    $telemetryTasks = @(Get-ScheduledTask -ErrorAction Stop | Where-Object {
        $_.TaskName -match 'Telemetry|CEIP|Customer'
    })

    foreach ($task in $telemetryTasks) {
        try {
            $taskChanges.Add([pscustomobject]@{
                TaskName = $task.TaskName
                TaskPath = $task.TaskPath
                OriginalState = [string]$task.State
            })
            Disable-ScheduledTask -TaskName $task.TaskName -TaskPath $task.TaskPath -ErrorAction Stop | Out-Null
            Write-Log "DISABLED scheduled task $($task.TaskPath)$($task.TaskName) (previous state: $($task.State))."
        }
        catch {
            Write-Log "SKIPPED scheduled task $($task.TaskPath)$($task.TaskName): $($_.Exception.Message)" 'WARN'
        }
    }
}
catch {
    Write-Log "Could not enumerate scheduled tasks: $($_.Exception.Message)" 'WARN'
}

$state = [pscustomobject]@{
    GeneratedAt = (Get-Date).ToString('o')
    ComputerName = $env:COMPUTERNAME
    LogPath = $logPath
    Services = @($serviceChanges)
    ScheduledTasks = @($taskChanges)
}
$state | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $statePath -Encoding UTF8

if (Test-Path -LiteralPath $undoPath) { Remove-Item -LiteralPath $undoPath -Force }
@'
# Generated by Windows 11 Service Optimizer. Restores the previous run only.
# Run as Administrator.
$ErrorActionPreference = 'Continue'
$root = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
$statePath = Join-Path $root 'optimizer-last-run.json'
if (-not (Test-Path -LiteralPath $statePath)) { Write-Error "State file not found: $statePath"; exit 1 }
$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) { Write-Error 'This script must be run as Administrator.'; exit 1 }
$state = Get-Content -LiteralPath $statePath -Raw | ConvertFrom-Json
foreach ($service in @($state.Services)) {
    try {
        $startupType = switch ($service.OriginalStartMode) { 'Auto' { 'Automatic' } 'Manual' { 'Manual' } 'Disabled' { 'Disabled' } default { 'Manual' } }
        Set-Service -Name $service.Name -StartupType $startupType -ErrorAction Stop
        if ($service.OriginalStatus -eq 'Running') { Start-Service -Name $service.Name -ErrorAction Stop }
        Write-Host "Restored service: $($service.Name)" -ForegroundColor Green
    } catch { Write-Warning "Could not restore service $($service.Name): $($_.Exception.Message)" }
}
foreach ($task in @($state.ScheduledTasks)) {
    try {
        if ($task.OriginalState -eq 'Disabled') {
            Disable-ScheduledTask -TaskName $task.TaskName -TaskPath $task.TaskPath -ErrorAction Stop | Out-Null
        } else {
            Enable-ScheduledTask -TaskName $task.TaskName -TaskPath $task.TaskPath -ErrorAction Stop | Out-Null
        }
        Write-Host "Restored scheduled task: $($task.TaskPath)$($task.TaskName)" -ForegroundColor Green
    } catch { Write-Warning "Could not restore scheduled task $($task.TaskPath)$($task.TaskName): $($_.Exception.Message)" }
}
Write-Host 'Undo completed. Review any warnings above.' -ForegroundColor Cyan
'@ | Set-Content -LiteralPath $undoPath -Encoding UTF8

Write-Log "Completed. Services changed: $changed; services skipped: $skipped; scheduled tasks captured: $($taskChanges.Count)."
Write-Log "Undo script: $undoPath"
Write-Host "`n📄 Detailed log: $logPath" -ForegroundColor Cyan
Write-Host "↩️ Undo script: $undoPath" -ForegroundColor Yellow
